# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import base64
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
from one_png import img as one  # 引入img变量，赋别名为one

tmp = open('one.png', 'wb')  # 创建临时的文件

tmp.write(base64.b64decode(one))  ##把这个one图片解码出来，写入文件中去。
tmp.close()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(Qt.NonModal)
        Form.setWindowFlags(Qt.FramelessWindowHint)
        Form.setEnabled(True)
        Form.resize(600, 500)
        Form.setContextMenuPolicy(Qt.NoContextMenu)
        palette = QPalette()
        pix = QPixmap("one.png")
        pix = pix.scaled(Form.width(), Form.height())
        palette.setBrush(QPalette.Background, QBrush(pix))
        Form.setPalette(palette)
        Form.setStyleSheet("*{\n"
"                font-size:24px;\n"
"                font-family:sans-serif;\n"
"                }\n"
"                #Form{\n"
#"                background-image:url(1.png);\n"
#"                background-color:#FAEBD7;\n"
"                }\n"
"                QFrame{\n"
"                background:rgba(0,0,0,0.8);\n"
"                border-radius:15px;\n"
"                }\n"
"                QPushButton{\n"
"                background:#03a9f4;\n"
"                color:#fff;\n"
"                border-radius:15px;\n"
"                }\n"
"                QLineEdit{\n"
"                border-radius:15px;\n"
"                color:#03a9f4;\n"
"                }\n"
"                QLabel{\n"
"                color:#fff;\n"
"                background:transparent;\n"
"                font-size:30px;\n"
"                }\n"
"            ")
        self.frame = QFrame(Form)
        self.frame.setGeometry(QRect(120, 110, 361, 251))
        self.frame.setStyleSheet("border:2px;\n"
"border-radius:5px;\n"
"padding:2px 4px;")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.loginID = QLineEdit(self.frame)
        self.loginID.setGeometry(QRect(20, 60, 321, 41))
        self.loginID.setStyleSheet("border:2px;\n"
"border-radius:5px;\n"
"padding:2px 4px;")
        self.loginID.setObjectName("loginID")
        self.loginPswd = QLineEdit(self.frame)
        self.loginPswd.setGeometry(QRect(20, 120, 321, 41))
        self.loginPswd.setStyleSheet("border:2px;\n"
"border-radius:5px;\n"
"padding:2px 4px;")
        self.loginPswd.setText("")
        self.loginPswd.setObjectName("loginPswd")
        self.label = QLabel(self.frame)
        self.label.setGeometry(QRect(70, 10, 201, 41))
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QRect(0, 170, 361, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginButton = QPushButton(self.horizontalLayoutWidget)
        self.loginButton.setStyleSheet("border:2px groove gray;\n"
"border-radius:5px;\n"
"padding:2px 4px;")
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        self.signinButton = QPushButton(self.horizontalLayoutWidget)
        self.signinButton.setStyleSheet("border-radius:5px;\n"
"padding:2px 4px;\n"
"border:2px groove gray;")
        self.signinButton.setObjectName("signinButton")
        self.horizontalLayout.addWidget(self.signinButton)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录"))
        self.loginID.setPlaceholderText(_translate("Form", "账号"))
        self.loginPswd.setPlaceholderText(_translate("Form", "密码"))
        self.label.setText(_translate("Form", "Login"))
        self.loginButton.setText(_translate("Form", "登录"))
        self.signinButton.setText(_translate("Form", "注册"))
