# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import base64

from PySide2.QtWidgets import *
from PySide2.QtGui import *
from PySide2.QtCore import *
from haimian_png import img as two  # 引入img变量，赋别名为one

...

tmp = open('two.png', 'wb')  # 创建临时的文件

tmp.write(base64.b64decode(two))  ##把这个one图片解码出来，写入文件中去。
tmp.close()



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1200,700)
        MainWindow.setAccessibleName("QO")
        MainWindow.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"padding:2px 4px;\n"
"font: 75 8pt \"微软雅黑\";")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(4, 1, 4, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listView = QListView(self.centralwidget)
        self.listView.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setBaseSize(QSize(0, 0))
        self.listView.setStyleSheet("border:2px groove gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"padding:2px 4px;")
        self.listView.setAutoScrollMargin(16)
        self.listView.setBatchSize(100)
        self.listView.setObjectName("listView")
        self.horizontalLayout_2.addWidget(self.listView)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setStyleSheet("border:2px groove gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"padding:2px 4px;")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 5, -1, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setStyleSheet("border:2px groove gray;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"padding:2px 4px;")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 11)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ResetButton = QPushButton(self.centralwidget)
        self.ResetButton.setStyleSheet("border:2px groove gray;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"padding:2px 4px;\n"
"background-color: rgb(0, 170, 255);\n"
"font: 75 8pt \"微软雅黑\";\n"
"")
        self.ResetButton.setObjectName("ResetButton")
        self.verticalLayout_3.addWidget(self.ResetButton)
        self.SendButton = QPushButton(self.centralwidget)
        self.SendButton.setStyleSheet("border:2px groove gray;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"padding:2px 4px;\n"
"background-color: rgb(0, 170, 255);\n"
"font: 75 8pt \"微软雅黑\";")
        self.SendButton.setIconSize(QSize(20, 30))
        self.SendButton.setObjectName("SendButton")
        self.verticalLayout_3.addWidget(self.SendButton)
        self.SendShortcut = QComboBox(self.centralwidget)
        self.SendShortcut.setStyleSheet("background-color:rgb(153,173,194);\n"
"border:2px groove gray;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 8pt \"微软雅黑\";")
        self.SendShortcut.setObjectName("SendShortcut")
        self.SendShortcut.addItem("")
        self.SendShortcut.addItem("")
        self.verticalLayout_3.addWidget(self.SendShortcut)
        self.verticalLayout_3.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.label = QLabel(self.centralwidget)
        self.label.setMaximumSize(QSize(250, 700))
        self.label.setText("")
        self.label.setPixmap(QPixmap("two.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(-1)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.horizontalLayout_3.setStretch(0, 1)


        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, 726, 25))
        self.menubar.setStyleSheet("background-color: rgb(153, 173, 194);\n"
"color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.menutest = QMenu(self.menubar)
        self.menutest.setObjectName("menutest")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionhelp = QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout =QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionaddfriend = QAction(MainWindow)
        self.actionaddfriend.setObjectName("actionaddfriend")
        self.action_app = QAction(MainWindow)
        self.action_app.setObjectName("action_app")
        self.actionexit = QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")

        self.actionstop = QAction(MainWindow)
        self.actionstop.setObjectName("actionstop")
        self.actioncontinue = QAction(MainWindow)
        self.actioncontinue.setObjectName("actioncontinue")
        self.actionrussia = QAction(MainWindow)
        self.actionrussia.setObjectName("actionrussia")


        self.menutest.addAction(self.actionaddfriend)
        self.menutest.addSeparator()
        self.menutest.addAction(self.actionexit)
        self.menutest.addAction(self.actionstop)
        self.menutest.addAction(self.actioncontinue)

        self.menutest.addAction(self.actionrussia)
        self.menu.addAction(self.actionhelp)
        self.menu.addAction(self.actionabout)
        self.menubar.addAction(self.menutest.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "开始聊天吧"))
        self.ResetButton.setText(_translate("MainWindow", "重 置"))
        self.SendButton.setText(_translate("MainWindow", "发 送"))
        self.SendShortcut.setItemText(0, _translate("MainWindow", "Ctrl+Enter"))
        self.SendShortcut.setItemText(1, _translate("MainWindow", "Enter"))
        self.menutest.setTitle(_translate("MainWindow", "选项"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.actionhelp.setText(_translate("MainWindow", "QO帮助"))
        self.actionabout.setText(_translate("MainWindow", "关于"))
        self.actionaddfriend.setText(_translate("MainWindow", "添加好友"))
        self.action_app.setText(_translate("MainWindow", "&app"))
        self.actionexit.setText(_translate("MainWindow", "退出"))
        self.actionstop.setText(_translate("MainWindow", "暂停音乐"))
        self.actioncontinue.setText(_translate("MainWindow", "播放音乐"))

        self.actionrussia.setText((_translate("MainWindow", "俄罗斯方块")))
import text
